Description: >
    Storage for Database
Parameters:
Resources:
MyAssign2DB:
    Type: AWS::RDS::DBInstance
    Properties: 
        AllocatedStorage: "1000"
        AvailabilityZone: us-west-2
        DBInstanceClass: "db.m4.large"
        DBName: Assign2DB
        Engine: "mysql"
        MasterUsername: "Assign2User"
        MasterUserPassword: "Assign2UserPass"
  
Outputs: 
    InstanceId:
        Description: InstanceId of the newly created RDS Instance
        Value: !Ref MyAssign2DB    